name: app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  get: ^4.6.5
  flutter_local_notifications: ^9.6.0
  flutter_native_timezone: ^2.0.0
  intl:
  google_fonts: ^4.0.4
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^8.0.0
  date_picker_timeline:
  sqflite: ^2.2.7
  flutter_staggered_animations: ^1.1.1
  line_awesome_flutter: ^2.0.0
  zoom_tap_animation: ^1.1.0
  http: ^0.13.6
  http_interceptor: ^1.0.2
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/


#  fonts:
#    - family: Mogra
#      fonts:
#        - asset: assets/fonts/Mogra.ttf
